<div class="contents">
	
	<h3 class="title">query</h3>
	
	<ul>
		<li><a href='/{$controller}/select'>select</a></li>
		<li><a href='/{$controller}/search'>search</a></li>
		<li><a href='/{$controller}/join'>join</a></li>
		<li><a href='/{$controller}/join2'>join2</a></li>
		<li><a href='/{$controller}/join3'>join3</a></li>
		<li><a href='/{$controller}/find'>find</a></li>
		<li><a href='/{$controller}/in'>in</a></li>
		<li><a href='/{$controller}/group'>group</a></li>
		<li><a href='/{$controller}/update'>update</a></li>
		<li><a href='/{$controller}/tableupdate'>table update</a></li>
		<li><a href='/{$controller}/info'>info</a></li>
		<li><a href='/{$controller}/textsearch'>textsearch</a></li>
		<li><a href='/{$controller}/array'>array</a></li>
		<li><a href='/{$controller}/cache'>cache</a></li>
	</ul>

</div>
