<div class="contents">
	<h3 class="title">text search</h3>

	<form action="/{$controller}/{$action}" method="get">
		<input type="text" name="t" value="{$t}"/><br />
		<input type="submit" /><br />
	</form>
</div>

{if $result}
<div class="contents">
{foreach from=$result item='row' name='loop1'}
	<b>{$row->name}</b><br />
	{$row->data|nl2br}<br />
<hr />
{/foreach}
</div>
{/if}
