<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html lang="ja">
<head>
<meta http-equiv="Content-Language" content="ja">
<meta http-equiv="Content-Type" content="text/html; charset={$charset}">
<title>{$title}</title>
<meta http-equiv="Content-Style-Type" content="text/css">
<style type="text/css"><!--
{literal}
 body{margin:0;padding:0;}
{/literal}
--></style>
</head>
<body>

{$body|nl2br}

{include file='inc/footer-html.phtml'}
</body>
</html>
