<div class="contents">
	side menu<br />
	<ul class="sidemenu">
		<li id="jquery"><a href="/jquery/">jQuery</a></li>
		<li id="test"><a href="/test/">動作確認</a></li>
		<li id="picture"><a href="/picture/">画像一覧</a></li>
		<li id="query"><a href="/query/">query</a></li>
		<li id="blog"><a href="/blog/">blog(routing)</a></li>
		<li id="twitter"><a href="/twitter/">twitter(oauth)</a></li>
	</ul>
</div>
