{head_meta
	description='description of this page'
	keywords='keyowrds,index'}
<div class="index contents">
	<h3 class="title">test project</h3><br />
	main content<br />
	<br />
	css tips<br />
	<br />
	css3のドロップシャドウやってみたが、<br />
	似たようなデザインのサイトが大量生産されて逆にダサくなる可能性。<br />
	要注意。IE非対応。<br />
	(ドロップシャドウ自体が素人くさい可能性も)<br />
	<br />
	
	<div class="logbox">
	{include file='inc/lemon.phtml'}
	</div>
	
	<br />
	dl　table
	<dl class="table">
		<dt>dt1</dt>
		<dd>dd1</dd>
		<dd>dd2</dd>
		<dd>dd3</dd>
		
		<dt>dt2</dt>
		<dd>dd1</dd>
		<dd>dd2</dd>
		<dd>dd3</dd>

	</dl>

</div>
