<div class="contents">
	<h3 class="title">サムネイル</h3>
	original size<br />
	<img src="{url name='media_image' owner='ashikawa' key='4' ext='jpg'}" /><br />
	<br />
	
	harf size(*0.5 *0.5)<br />
	<img src="{url name='media_imageT' owner='ashikawa' key='4' ext='jpg' mode='s'}" /><br />
	<br />

	fit(in area 100 * 100)<br />
	<img src="{url name='media_imageT' owner='ashikawa' key='4' ext='jpg' mode='f'}" /><br />
	<br />

	canvas fit + background (100 * 100)<br />
	<img src="{url name='media_imageT' owner='ashikawa' key='4' ext='jpg' mode='c'}" /><br />
	<br />

</div>
