<div class="contents">
	
	<h3 class="title">動作確認</h3>
	
	<ul>
		<li><a href="/{$controller}/map">google map</a></li>
		<li><a href="/{$controller}/google">google api</a></li>
		<li><a href="/{$controller}/amazon">amazon</a></li>
		<li><a href="/{$controller}/youtube">youtube</a></li>
		<li><a href="/{$controller}/qrcode">qr code</a></li>
		<li><a href="/{$controller}/feed">feed</a></li>
		<li><a href="/{$controller}/log">log</a></li>
		<li><a href="/{$controller}/smarty">smarty</a></li>
		<li><a href="/{$controller}/foward">foward</a></li>
		<li><a href="/{$controller}/translate">translate</a></li>
		<li><a href="/{$controller}/escape">escape</a></li>
		<li><a href="/{$controller}/mail">mail</a></li>
		<li><a href="/{$controller}/exception">exception</a></li>
		<li><a href="/{$controller}/cookie">cookie</a></li>
		<li><a href="/{$controller}/cookie2">cookie2</a></li>
		<li><a href="/{$controller}/requestheder">requestheder</a></li>
		
		<li><a href="/{$controller}/mixi">mixi</a></li>
		<li><a href="/{$controller}/twitter">twitter</a></li>
		
		<li><a href="/{$controller}/mecab">mecab</a></li>
		
		<li><a href="/media/calender.ics">calender.ics</a></li>
		<li><a href="/media/calender.xml">calender.xml</a></li>
		
		<li><a href="{url name="media_pdf" file="ほげもげ.pdf"}" target="_blank">pdf</a></li>
		<li><a href="{url name="media_csv" file="ほげもげ.csv"}">csv</a></li>
	</ul>

<!--//end div#amazon--></div>
