<style type="text/css">
.carouselContainer{
	width: 200px;
	overflow: hidden;
}
.carousel{
	margin: auto;
}
#navi li{
	float: left;
}
</style>
<div class="contents">
	<h3 class="title">carousel</h3>
	
	
	<ul id="navi">
		<li id="prev">&lt;</li>
		<li id="navi1">[1]</li>
		<li id="navi2">[2]</li>
		<li id="navi3">[3]</li>
		<li id="navi4">[4]</li>
		<li id="navi5">[5]</li>
		<li id="next">&gt;</li>
	</ul>
	
	<div class="carouselContainer" style="clear: left;">
		<div class="carousel">
			<ul>
				<li><img src="/img/browsers/one.png" /></li>
				<li><img src="/img/browsers/two.png" /></li>
				<li><img src="/img/browsers/three.png" /></li>
				<li><img src="/img/browsers/four.png" /></li>
				<li><img src="/img/browsers/five.png" /></li>
			</ul>
		</div>
	</div>
<!--//end div.contents--></div>

{literal}
<script type="text/javascript" src="/js/jquery.bCarousel.js"></script>
<script type="text/javascript">
$(function() {
	
	var	startPosition	= 0
		, prevId		= "#prev"
		, nextId		= "#next";
	
	$(".carousel").bCarouselLite({
		btnNext: nextId,
		btnPrev: prevId,
		btnEvent: "click",
		btnGo: ["#navi1", "#navi2", "#navi3", "#navi4", "#navi5"],
		visible: 1,
		start: startPosition,
		circular: false,
		beforeStart: function(a, i){},
		afterEnd: function(a, i){}
	});
});
</script>
{/literal}