
<div class="contents">
	<h3 class="title">css3 animation</h3>
	
	CSS3製アニメーション。<br />
	Opera, Chromeのみ対応。　残念。<br />
	<div class="menuHolder">
		<div class="menu">
			<a href="#url"><img src="/img/browsers/one.png" alt="" /></a>
			<a href="#url"><img src="/img/browsers/two.png" alt="" /></a>
			<a href="#url"><img src="/img/browsers/three.png" alt="" /></a>
			<a href="#url"><img src="/img/browsers/four.png" alt="" /></a>
			<a href="#url"><img src="/img/browsers/five.png" alt="" /></a>
			<a href="#url"><img src="/img/browsers/six.png" alt="" /></a>
			<a href="#url"><img src="/img/browsers/seven.png" alt="" /></a>
			<a href="#url"><img src="/img/browsers/eight.png" alt="" /></a>
		</div>
	</div>
</div>
