<div class="contents">
	<h3 class="title">dPassword</h3>
	
	<form action="/{$controller}/{$action}">
		<input type="password" />
	</form>
	
<!--//end div#jquery--></div>


{literal}
<script type="text/javascript" src="/js/jquery.dPassword.js"></script>

<script type="text/javascript">
	$(document).ready(function (){
		var options = {};
		$('input[type=password]').dPassword(options);
	});
</script>
{/literal}