
<div class="contents">
<h3 class="title">jQuery</h3>
<ul>
	<li><a href="/{$controller}/accordion">accordion</a></li>
	<li><a href="/{$controller}/disable">disable</a></li>
	<li><a href="/{$controller}/checkgroup">check group</a></li>
	<li><a href="/{$controller}/resize">resize</a></li>
	<li><a href="/{$controller}/options">options</a></li>
	<li><a href="/{$controller}/zip">zip</a></li>
	<li><a href="/{$controller}/thickbox">thickbox</a></li>
	<li><a href="/{$controller}/calendar">calendar</a></li>
	<li><a href="/{$controller}/autocomplete">autocomplete</a></li>
	<li><a href="/{$controller}/sortable">sortable</a></li>
	<li><a href="/{$controller}/plugin">plugin</a></li>
	<li><a href="/picture/">thumbnail</a></li>
	<li><a href="/account_entry/">validate</a></li>
	<li><a href="/{$controller}/cssmenu">css menu</a></li>
	<li><a href="/{$controller}/tile">tile</a></li>
	<li><a href="/{$controller}/dpassword">dpassword</a></li>
	<li><a href="/{$controller}/data">data</a></li>
	<li><a href="/{$controller}/apply">apply</a></li>
	<li><a href="/{$controller}/sandbox">sandbox</a></li>
	<li><a href="/{$controller}/curry">sandbox</a></li>
	<li><a href="/{$controller}/carousel">carousel</a></li>
	<li><a href="/{$controller}/osm">osm</a></li>
</ul>

<!--//end div#amazon--></div>
