<div class="contents">
	<h3 class="title">sandbox</h3>
	<br />
	プラグインの雛形。<br />
	@tosee {"http://www.ibm.com/developerworks/jp/web/library/wa-aj-jquery6/index.html"|link}<br />
	
<!--//end div#contents--></div>

{literal}
<script type="text/javascript">
;(function($) {
	$.budori = $.budori || {};

	$.fn.extend({
		sample: function() {
			console.log('flag1');
			$.data(this, "budori-sample", new $.budori.sample(this, []));
			return this;
		},
	});
	
	$.budori.sample = function(container, options) {
		console.log('flag2');
	};
	
	$.budori.sample.prototype = {
		hoge: function() {
			console.log('flag3');
			moge();
		}
	}
	
	function moge(){
		console.log('flag4');
	}
})(jQuery);

	$(document).ready(function (){
		var target = $("div.target").sample();
		console.log('------');
		$.data(target,'budori-sample').hoge();
	});
</script>
{/literal}